Join documentation, sample and JS bundle
derapi/derapi pull request #2
Opened 2024-03-28 15:10 UTC by iblatter

#573

2024-03-28 15:52 UTC, mdebenedittis requested changes
left comments inline, thank you!

2024-03-28 15:52 UTC, mdebenedittis commented on join/README.md
> +Derapi Join allows site owners to grant you access to their systems.
I think we should standardize on "end-customers". In this case instead of "site owners"

2024-03-28 15:52 UTC, mdebenedittis commented on join/README.md
> +<script src="https://raw.githubusercontent.com/derapi/derapi/main/join/derapi-join.js"></script>
I get a 404 when I try to access this resource. I assume this is expected since it has not merged.

2024-03-28 15:52 UTC, mdebenedittis commented on join/README.md
> +Derapi Join requires a Join session to be created.  A POST request to https://api.derapi.com/join/session/start will return a `session_id` as documented [here](https://api.derapi.com/apidocs/#/Join/p
Instead of "as documented here". Can we say "as documented in the [Derapi API Reference]"

2024-03-28 15:52 UTC, mdebenedittis commented on join/README.md
> +```
suggest syntax highlighting by adding javascript after the ticks:
"```javascript"

2024-03-28 15:52 UTC, mdebenedittis commented on join/README.md
> +```
It will look like this. fun!
```javascript
        import derapi from "https://raw.githubusercontent.com/derapi/derapi/main/join/derapi-join.js";
        const onSuccess = () => {
            alert('success!');
        }
        const onClose = () => {
            alert('closed');
        }
        const join = derapi.createJoin(sessionToken, onSuccess, onClose, derapiToken);
        join.open();
```

2024-03-28 15:52 UTC, mdebenedittis commented on join/README.md
> +Once the site owner has authenticated and you receive the `onSuccess()` callback, simply call https://api.derapi.com/join/session/{session_id}/fetch-token to retrieve the public token that can be use
Same comment on **site owner** vs **end-customer**. Also same comment on "documented [here]"

2024-03-28 15:52 UTC, mdebenedittis commented on join/join-sample.html
> +        <div style="height: 450px; display: flex; flex-direction: column; background-image: url(https://news.mit.edu/sites/default/files/styles/news_article__image_gallery/public/images/202006/MIT-PP
can we host the image we use in the demo on github instead?

2024-03-28 15:52 UTC, mdebenedittis commented on join/join-sample.html
> +        <div style="height: 450px; display: flex; flex-direction: column; background-image: url(https://news.mit.edu/sites/default/files/styles/news_article__image_gallery/public/images/202006/MIT-PP
This one renders oddly
<img width="1446" alt="image" src="https://github.com/derapi/derapi/assets/1616388/e58fcaa9-4924-46ae-9f19-98ce2a54bfc9">

2024-03-29 21:54 UTC, iblatter commented on join/README.md
> +<script src="https://raw.githubusercontent.com/derapi/derapi/main/join/derapi-join.js"></script>
yep, exactly

2024-03-29 22:02 UTC, iblatter commented on join/join-sample.html
> +        <div style="height: 450px; display: flex; flex-direction: column; background-image: url(https://news.mit.edu/sites/default/files/styles/news_article__image_gallery/public/images/202006/MIT-PP
done, but won't render until this is merged

2024-03-29 22:02 UTC, iblatter commented on join/README.md
> +Once the site owner has authenticated and you receive the `onSuccess()` callback, simply call https://api.derapi.com/join/session/{session_id}/fetch-token to retrieve the public token that can be use
fixed this

2024-03-29 22:02 UTC, iblatter commented on join/README.md
> +```
thanks for that.  It's really cool

2024-03-29 22:02 UTC, iblatter commented on join/README.md
> +Derapi Join requires a Join session to be created.  A POST request to https://api.derapi.com/join/session/start will return a `session_id` as documented [here](https://api.derapi.com/apidocs/#/Join/p
done

2024-03-29 22:02 UTC, iblatter commented on join/README.md
> +Derapi Join allows site owners to grant you access to their systems.
done

2024-03-30 02:15 UTC, mdebenedittis approved these changes
thanks!

2024-03-30 02:16 UTC, merged